<?php
/**
 * 模型字段模板文件
 * 用于自动生成模型字段类
 * 
 * 模板变量说明：
 * - {{TABLE_NAME}}: 表名（转换为PascalCase）
 * - {{TABLE_NAME_ORIGINAL}}: 原始表名
 * - {{FIELDS}}: 字段常量定义
 * - {{FIELD_CONSTANTS}}: getAll()方法中的字段常量数组
 * - {{TIMESTAMP}}: 生成时间
 */

return <<<'TEMPLATE'
<?php
// =================================================================================
// This is auto-generated by shell command, don't modify it.
// =================================================================================
namespace App\Models\Fields;

/**
 * {{TABLE_NAME}}Field 模型字段类
 * {{TABLE_NAME_ORIGINAL}}
 */
class {{TABLE_NAME}}Field
{
{{FIELDS}}
    /**
     * 字段: _TABLE_NAME - 表名
     */
    const _TABLE_NAME_ = '{{TABLE_NAME_ORIGINAL}}';
    
    /**
     * 获取所有字段常量
     */
    public static function getAll()
    {
        return [
            {{FIELD_CONSTANTS}}
        ];
    }
    
    /**
     * 获取表名
     */
    public static function getTableName()
    {
        return '{{TABLE_NAME_ORIGINAL}}';
    }
}
TEMPLATE;